// Generated by CoffeeScript 1.7.1
(function() {
  var config, root;

  config = require('../utils/getConfig');

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.test = function(req, res) {
    return res.send('test');
  };

  root.intro = function(req, res) {
    return res.sendfile('public/intro.html');
  };

  root.console = function(req, res) {
    var t;
    t = {
      data: config,
      title: "see"
    };
    return res.render('console', t);
  };

  root.submit = function(req, res) {
    return res.send('success');
  };

  root.sync = function(req, res) {
    return res.send('suceess');
  };

}).call(this);
