// Generated by CoffeeScript 1.7.1
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.test = function(req, res) {
    return res.send('test');
  };

}).call(this);
